-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 19, 2022 at 03:24 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movie_aldin`
--

-- --------------------------------------------------------

--
-- Table structure for table `film`
--

CREATE TABLE `film` (
  `imdb_id` varchar(10) CHARACTER SET utf8 NOT NULL,
  `title` varchar(49) CHARACTER SET utf8 DEFAULT NULL,
  `certificate` varchar(5) CHARACTER SET utf8 DEFAULT NULL,
  `startYear` int(11) DEFAULT NULL,
  `endYear` int(11) DEFAULT NULL,
  `type` varchar(26) CHARACTER SET utf8 DEFAULT NULL,
  `orign_country` varchar(14) CHARACTER SET utf8 DEFAULT NULL,
  `plot` varchar(232) CHARACTER SET utf8 DEFAULT NULL,
  `summary` varchar(1749) CHARACTER SET utf8 DEFAULT NULL,
  `genres` varchar(26) CHARACTER SET utf8 DEFAULT NULL,
  `isAdult` int(11) DEFAULT NULL,
  `cast` varchar(409) CHARACTER SET utf8 DEFAULT NULL,
  `image_url` varchar(154) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `film`
--

INSERT INTO `film` (`imdb_id`, `title`, `certificate`, `startYear`, `endYear`, `type`, `orign_country`, `plot`, `summary`, `genres`, `isAdult`, `cast`, `image_url`) VALUES
('mn001', 'Iron Man', '15', 2008, NULL, 'Movie,Action', 'United States', 'A wealthy industrialist (Robert Downey Jr.) builds an armored suit and uses it to defeat criminals and terrorists.', 'Tony Stark. Genius, billionaire, playboy, philanthropist. Son of legendary inventor and weapons contractor Howard Stark. When Tony Stark is assigned to give a weapons presentation to an Iraqi unit led by Lt. Col. James Rhodes, he\'s given a ride on enemy lines. That ride ends badly when Stark\'s Humvee that he\'s riding in is attacked by enemy combatants. He survives - barely - with a chest full of shrapnel and a car battery attached to his heart. In order to survive he comes up with a way to miniaturize the battery and figures out that the battery can power something else. Thus Iron Man is born. He uses the primitive device to escape from the cave in Iraq. Once back home, he then begins work on perfecting the Iron Man suit. But the man who was put in charge of Stark Industries has plans of his own to take over Tony\'s technology for other matters. —halo1k', 'Action,Fantasy', 0, '[\'Robert Downey Jr\', \'Gwyneth Paltrow\']', 'https://image.tmdb.org/t/p/original/gq2oNHDu71eQJPZlMp6nMsbb2KW.jpg'),
('mn002', 'The Incredible Hulk', '18', 2008, NULL, 'Movie,Action', 'United States', 'As Bruce Banner (Edward Norton) seeks to rid himself of The Hulk forever, a powerful enemy known as The Abomination arises to wreak havoc on the human race.', 'Depicting the events after the Gamma Bomb. The Incredible Hulk tells the story of Dr Bruce Banner, who seeks a cure to his unique condition, which causes him to turn into a giant green monster under emotional stress. Whilst on the run from military which seeks his capture, Banner comes close to a cure. But all is lost when a new creature emerges: The Abomination. —Graham Kroon', 'Action,Fantasy', 0, '[\'Edward Norton\', \'Liv Tyler\']', 'https://image.tmdb.org/t/p/w1280/g8iR8JjSNSYLAD9Y5eAnxE9oVIJ.jpg'),
('mn003', 'Iron Man 2', '18', 2010, NULL, 'Movie,Action', 'United States', 'With the world now aware that he is Iron Man, billionaire inventor Tony Stark (Robert Downey Jr.) must forge new alliances and confront a powerful new enemy.', 'After Tony Stark announces to the World that he\'s Iron Man. He faces many problems in his Life, His Lifesource is Poisoning him, The US Government wants his tech, and someone\'s out to kill Stark. That Someone is Ivan Vanko, Son of Anton Vanko who worked with Tony\'s Father Howard, But Howard then sent Anton to Russia. Ivan trys to kill Tony Stark at a Grand Prix in Monaco but Ivan is then arrested. However Tony\'s Rival Justin Hammer helps Vanko escape from Prison and Hires Vanko to create to Suits similar to Tonys. Tony also assigns his Assistant Pepper Potts as CEO of Stark Industries. It\'s now up to Tony to defeat Ivan and Hammer and to fix his Arc Reactor before he can die. —ahmetkozan', 'Action, Fantasy', 0, '[\'Robert Downey Jr\', \'Gwenyth Paltrow\']', 'https://vignette.wikia.nocookie.net/marveldatabase/images/e/ed/Iron_Man_2_poster.jpg/revision/latest?cb=20190309193419'),
('mn004', 'Thor', '13+', 2011, NULL, 'Movie,Action', 'United States', 'After his reckless actions reignite an ancient war, the Norse god (Chris Hemsworth) is stripped of his powers, cast out of Asgard and forced to live among humans.', 'After wanting to wage war against the Frost Giants, the mighty warrior Thor (Chris Hemsworth) is cast out from Asgard by his father Odin (Sir Anthony Hopkins) and sent down to Earth. With no way home, and his hammer Mjölnir lost, Thor struggles to reclaim his powers. Meanwhile, on Asgard, Thor\'s devious brother Loki (Tom Hiddleston) had seized the throne and seeks to help the Frost Giants reclaim their glory. With help from scientist Jane Foster (Natalie Portman) and her team, Thor must learn the true virtue of being a hero and return home to stop Loki and save Asgard from destruction. —Blazer346', 'Action,Fantasy', 0, '[\'Chris Hemsworth\', \'Natalie Portman\']', 'http://4.bp.blogspot.com/--nPEMSyLyo8/TcGCkDuk2jI/AAAAAAAAHFQ/bxxUOo_JIe0/s1600/thor-international-poster-02.jpg'),
('mn005', 'Captain America: The First Avenger', '18', 2011, NULL, 'Movie,Action', 'United States', 'After an experimental program turns him into a supersoldier, Steve Rogers (Chris Evans), now known as Captain America, leads the fight against Red Skull\'s evil HYDRA organization.', 'At the outset of World War II, Steve Rogers wants nothing more than to join the army. The only problem is that he can\'t pass the physical. He\'s tried several times under different names without success. Dr. Abraham Erskine notes his eagerness and recruits him for an experimental project. Rogers is soon transformed, both mentally and physically, into a super soldier where he eventually faces off against the Nazi organization Hydra and its head, known as Red Skull. —garykmcd', 'Action,Fantasy', 0, '[\'Chris Evans\', \'Hayley Atwell\']', 'https://2.bp.blogspot.com/-mSaFthwKB4E/U1WyDZxaLpI/AAAAAAAAH_8/iIqOEFD6IgA/s1600/thefirstavengerposter.jpg'),
('mn006', 'The Avenger', '18', 2011, NULL, 'Movie,Action', 'United States', 'S.H.I.E.L.D.\'s Nick Fury (Samuel L. Jackson) recruits a team of superheroes to pull the world back from the brink of disaster when an unexpected enemy threatens global security.', 'S.H.I.E.L.D. has located the mysterious Tesseract device and the Army\'s super soldier Captain America. The Tesseract is actually a gateway to an entirely new world called Asgard. A mysterious being known as Loki arrives on earth and immediately assumes that he can rule all human beings. But that irks S.H.I.E.L.D. director Nick Fury the wrong way. As Loki escapes with the Tesseract, Nick Fury believes this is an act of war against Earth. His only hope is to assemble an actual team of super heroes. Dr. Bruce Banner, who turns into an enormous green rage monster known as the Hulk. Tony Stark and his venerable Iron Man armor. Captain America, the Stark Enterprises created super soldier. Thor, the god of thunder, protector of Earth and his home planet of Asgard, and Loki\'s brother. Master assassins Hawkeye and Natasha Romanoff. Together they will become a team to take on an attack that will call them to become the greatest of all time. —halo1k', 'Action,Fantasy', 0, '[\'Robert Downey Jr\', \'Chriss Evans\', \'Mark Ruuffalo\']', 'https://vignette.wikia.nocookie.net/marvelmovies/images/8/8f/2012_Avengers_Poster.jpg/revision/latest?cb=20140224212535'),
('mn007', 'Iron Man 3', '15+', 2013, NULL, 'Movie,Action', 'United States', 'After a malevolent enemy reduces his world to rubble, Tony Stark (Robert Downey Jr.) must rely on instinct and ingenuity to protect those he loves as he searches for a way to avenge his losses.', 'Marvel\'s Iron Man 3 pits brash-but-brilliant industrialist Tony Stark/Iron Man against an enemy whose reach knows no bounds. When Stark finds his personal world destroyed at his enemy\'s hands, he embarks on a harrowing quest to find those responsible. This journey, at every turn, will test his mettle. With his back against the wall, Stark is left to survive by his own devices, relying on his ingenuity and instincts to protect those closest to him. As he fights his way back, Stark discovers the answer to the question that has secretly haunted him: does the man make the suit or does the suit make the man? —Jawadjee', 'Action,Fantasy', 0, '[\'Robert Downey Jr\', \'Gwenyth Paltrow\']', 'http://www.comicbookcritic.net/wp-content/uploads/2013/03/IRON3_5x8_Banner_v7_OL.jpg'),
('mn008', 'Thor: The Dark World', '16', 2013, NULL, 'Movie,Action', 'United States', 'Thor (Chris Hemsworth) forms an alliance with treacherous Loki (Tom Hiddleston) to save Earth and the Nine Realms from an ancient enemy that predates the universe itself.', 'A year after Loki\'s (Tom Hiddleston\'s) devastating alien attack on New York City, the Mighty Thor (Chris Hemsworth), along with his friends Lady Sif (Jaimie Alexander) and the Warriors Three fight to save the Nine Realms from deadly threats. When Thor\'s girlfriend Jane Foster (Natalie Portman) discovers a fluid like weapon called the Aether, she unknowingly awakens the evil Malekith (Christopher Eccleston) and his Dark Elf army. With this, Asgard may be facing its darkest hour. Thor forms an uneasy alliance with his nemesis Loki to save Jane, stop Malekith, and save the Nine Realms from total chaos and darkness. —ahmetkozan', 'Action,Fantasy', 0, '[\'Chris Hemswort\', \'Natalie Portman\', \'Tom Hiddleston\']', 'http://media.comicbook.com/wp-content/uploads/2013/09/Thor_Un_Mundo_Oscuro_Poster_Latino_ex_JPosters.jpg'),
('mn009', 'Captain America: The Winter Soldier', '16+', 2014, NULL, 'Movie,Action', 'United States', 'Captain America (Chris Evans), the Black Widow (Scarlett Johansson) and a new ally, the Falcon, face an unexpected enemy as they struggle to expose a far-reaching conspiracy that puts the world at risk.', 'Steve Rogers is coming to grips with living in modern America after being frozen in ice for 50 years. A new threat against S.H.I.E.L.D. arises called \"The Winter Soldier\". While the origins of the Winter Soldier are unknown, the threat against S.H.I.E.L.D. from the Hydra organization is. Especially after it compromises Nick Fury and Agent Romanoff, leaving them betrayed and left for dead, and their S.H.I.E.L.D. status revoked, marking them as traitors to the organization. Now racing against time with very little resources available at his disposal, Captain America launches an investigation into S.H.I.E.L.D.\'s origins and that has him returning to the very Army base where he once underwent basic training nearly 100 years ago. What he and Romanoff discover there leads to a very startling development with S.H.I.E.L.D., a top secret project called \"Operation Insight\", and the launch of the next generation of Helicarrier. Can they stop it before it\'s too late? —halo1k', 'Action,Fantasy', 0, '[\'Chris Evans\', \'Scarlett Johansen\', \'Sebastian Stann\']', 'https://www.scannain.com/media/captain-america-the-winter-soldier_poster-1.jpg'),
('mn010', 'Guardian of the Galaxy', '18', 2014, NULL, 'Movie,Action', 'United States', 'A space adventurer (Chris Pratt) becomes the quarry of bounty hunters after he steals an orb coveted by a treacherous villain, but after he discovers the orb\'s true power, he must find a way to unite four ragtag rivals to save the u', 'After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the \"Guardians of the Galaxy\" to save the galaxy. —James Hake', 'Action,Fantasy', 0, '[\'Chris Pratt\', \'Dave Bautista\', \'Vin Diessel\']', 'https://static0.colliderimages.com/wordpress/wp-content/uploads/guardians-of-the-galaxy-movie-poster1.jpg'),
('mn011', 'Avenger: Age of Ultron', '13+', 2015, NULL, 'Movie,Action', 'United States', 'When Tony Stark\'s (Robert Downey Jr.) jumpstart of a dormant peacekeeping program goes awry, the Avengers must reassemble to battle a terrifying technological villain hell-bent on human extinction.', 'Since the events of the last film, the Avengers have been working to take down various cells of a secret society of villains known as HYDRA. Their zeal to make the world a better, safer place inspires Tony Stark, genius billionaire and alter ego of Iron Man, to create Ultron in order to respond to additional threats that the Avengers aren\'t able to handle. Ultron, unfortunately, takes this directive too seriously -- he believes that world peace can only be achieved by exterminating humanity, and he\'ll stop at nothing to accomplish this goal. The battle between the Avengers and Ultron is further complicated by the appearance of super-powered siblings Quicksilver and Scarlet Witch, who ally themselves with the homicidal android.', 'Action,Fantasy', 0, '[\'Robert Downey Jr\', \'Chris Evans\', \'Mark Ruffalo\']', 'http://thesource.com/wp-content/uploads/2015/04/Avengers_Age_Of_Ultron-poster1.jpg'),
('mn012', 'Ant-Man', '18+', 2015, NULL, 'Movie,Action', 'United States', 'Armed with a suit that allows him to shrink in size but grow in strength, Ant-Man (Paul Rudd) must prevent Dr. Hank Pym\'s former protégé (Corey Stoll), also known as Yellowjacket, from perfecting the same technology and using it as ', 'After serving a few years in prison, former burglar Scott Lang is released. Now wanting to be straight, Scott sets out to find himself a job. But he is totally unaware that his record is preventing him from working and seeing his young daughter Cassie. When he steals a powerful suit, he quickly returns it only to find himself arrested again. But a mysterious man named Hank Pym has other ideas for him. Pym explains that it has the power  to shrink in size and increase in strength due to a special formula called the Pym Particle. He was once its owner and called himself Ant-Man. Unfortunately during his SHIELD days, Pym discovers that others wanted to replicate his design. Now Pym wants to use Scott to being the new Ant-Man because his former apprentice Darren Cross is working to replicate the formula for his own evil purposes. So Scott and Pym, along with Pym\'s daughter Hope must plan a heist that will stop Cross and save the world from certain chaos. —Blazer346', 'Action,Fantasy', 0, '[\'Paul Rudd\', \'Michael Douglass\']', 'https://www.newdvdreleasedates.com/images/posters/large/ant-man-2015-03.jpg'),
('mn013', 'Captain America: Civil Wars', 'A', 2016, NULL, 'Movie,Action', 'United States', 'Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner) must pick a side when a feud between Captain America (Chris Evans) and Iron Man (Robert Downey Jr.) leaves the Avengers in turmoil.', 'With many people fearing the actions of super heroes, the government decides to push for the Hero Registration Act, a law that limits a hero\'s actions. This results in a division in The Avengers. Iron Man stands with this Act, claiming that their actions must be kept in check otherwise cities will continue to be destroyed, but Captain America feels that saving the world is daring enough and that they cannot rely on the government to protect the world. This escalates into an all-out war between Team Iron Man (Iron Man, Black Panther, Vision, Black Widow, War Machine, and Spider-Man) and Team Captain America (Captain America, Bucky Barnes, Falcon, Scarlet Witch, Hawkeye, and Ant Man) while a new villain emerges. —RespectTheHyphen', 'Action,Fantasy', 0, '[\'Chris Evans\', \'Robert Downey Jr\']', 'http://heroichollywood.com/wp-content/uploads/2016/04/teamcapposter.jpg'),
('mn014', 'Doctor Strange', '16', 2016, NULL, 'Movie,Action', 'United States', 'After a terrible accident, Dr. Stephen Strange (Benedict Cumberbatch) loses his ability to operate but finds new purpose when a mystical being known as the Ancient One reveals that Dr. Strange is the newly designated Sorcerer Suprem', 'After a horrible car accident, brilliant neurosurgeon Stephen Strange must find a way and a cure to healing his hands. His quest brings him to Kamar-Taj in Nepal where he studies under the Ancient One, who teaches him the ways of magic and alternate realities. With new skills of interdimensional travel and spells, Strange soon discovers that he must protect the world from a deadly enemy who is out to destroy it. —Blazer346', 'Action,Fantasy', 0, '[\'Benedict Cumberbatch\', \'Rachel McAdams\']', 'https://cdn.traileraddict.com/content/walt-disney-pictures/doctor-strange-6.jpg'),
('mn015', 'Guardian of the Galaxy Vol. 2', '18', 2017, NULL, 'Movie,Action', 'United States', 'The team struggles to keep its newfound family together as it tries to unravel the mystery of Peter Quill\'s true parentage in the outer reaches of the galaxy.', 'After saving Xandar from Ronan\'s wrath, the Guardians are now recognized as heroes. Now the team must help their leader Star Lord (Chris Pratt) uncover the truth behind his true heritage. Along the way, old foes turn to allies and betrayal is blooming. And the Guardians find that they are up against a devastating new menace who is out to rule the galaxy. —Blazer346', 'Action,Fantasy', 0, '[\'Chris Pratt\', \'Dave Bautista\', \'Zoe Saldana\']', 'http://www.blackfilm.com/read/wp-content/uploads/2017/03/Guardians-of-the-Galaxy-Vol.-2-Poster.jpg'),
('mn016', 'Spider-Man: Homecoming', '18', 2017, NULL, 'Movie,Action', 'United States', 'Under the watchful eye of mentor Tony Stark, high school student Peter Parker starts to embrace his newfound identity as Spider-Man to battle the evil Vulture.', 'A young Peter Parker/Spider-Man begins to navigate his newfound identity as the web-slinging super hero Spider-Man. Thrilled by his experience with the Avengers, Peter returns home, where he lives with his Aunt May, under the watchful eye of his new mentor Tony Stark. Peter tries to fall back into his normal daily routine - distracted by thoughts of proving himself to be more than just your friendly neighborhood Spider-Man - but when the Vulture emerges as a new villain, everything that Peter holds most important will be threatened. —Flick Direct', 'Action,Fantasy', 0, '[\'Tom Holland\', \'Robert Downey Jr\', \'Zendaya\', \'Happy Hogan\']', 'https://media.vanityfair.com/photos/592592596736887ada186bcd/master/w_1024%2Cc_limit/spider-man-homecoming-SMH_DOM_Online_FNL_1SHT_3DRD3DIMX_AOJ_300dpi_01'),
('mn017', 'Thor: Ragnarok', '13', 2017, NULL, 'Movie,Action', 'United States', 'Thor must battle the Hulk in a deadly gladiatorial contest and prevent the all-powerful Hela from destroying his home world and the Asgardian civilization.', 'After the events of Avengers: Age of Ultron (2015), and four years after the events of Thor: The Dark World (2013), Thor (Chris Hemsworth), held captive on the planet Sakaar without his hammer, must win a gladiatorial duel against The Incredible Hulk (Mark Ruffalo) and assemble a team (made up of The Incredible Hulk, Valkyrie (Tessa Thompson), Thor, and Loki (Tom Hiddleston)) to stop the villainous Hela (Cate Blanchett) and the impending Ragnarök, the doom of the Asgardian civilization. —priba_dj', 'Action,Fantasy', 0, '[\'Chris Hemsworth\', \'Mark Ruffalo\']', 'https://tse4.mm.bing.net/th?id=OIP.8UFP29_AUjoRk-AUxPEcagHaK-&pid=Api&P=0&w=132&h=196'),
('mn018', 'Black Panther', '13', 2018, NULL, 'Movie,Action', 'United States', 'Black Panther\'s mettle as king gets tested when an old enemy draws him into a conflict that puts his nation and the world at risk. The king must soon rally his allies and release his full power to defeat his foes and secure the safe', 'Follows T\'Challa who, after the death of his father, the King who of Wakanda, returns home to the isolated, technologically advanced African nation to succeed to the throne and take his rightful place as king. But when a powerful old enemy reappears, T\'Challa\'s mettle as king and Black Panther is tested when he is drawn into a formidable conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people and their way of life. —ahmetkozan', 'Action,Fantasy', 0, '[\'Chadwick Boseman\', \'Michael B Jordan\']', 'https://2.bp.blogspot.com/-YmckzmVCItg/WsRiX8OOteI/AAAAAAAAAEM/1S71WO8nhxojKHkTtmzYIncvzbl75bztwCLcBGAs/w680/black-panther-poster.jpg'),
('mn019', 'Avenger: Infinity War', '13', 2018, NULL, 'Movie,Action', 'United States', 'Iron Man, Thor, the Hulk and the rest of the Avengers unite to battle the evil Thanos -- an intergalactic despot who plans to use all six Infinity Stones to inflict his twisted will on reality.', 'Now that Earth has put its mark on the universe through the Avengers, all superheroes, including ones from other parts of the Galaxy, must join forces to stop the powerful Thanos from taking all the infinity stones and destroying the universe one planet at a time. —Joshua Chandler', 'Action,Fantasy', 0, '[\'Robert Downey Jr\', \'Chris Evans\', \'Chris Hemsworth\', \'Josh Brolin\']', 'https://tse1.mm.bing.net/th?id=OIP.wz2wMvsejpPPKnzKx11oNAHaK-&pid=Api&P=0&w=137&h=204'),
('mn020', 'Ant-Man and The Wasp', '18', 2018, NULL, 'Movies,Action', 'United States', 'Approached by Hope van Dyne and Dr. Hank Pym, Scott Lang once again dons the Ant-Man suit to fight alongside the Wasp. The mission soon leads to secret revelations from the past as the duo finds itself in an epic battle against a po', 'In the aftermath of his experiences in Germany with the Avengers, Scott Lang must now deal with the consequences of his past actions while under house arrest. But Scott answers a call back into action when Hope Van Dyne and Dr. Hank Pym approach him with a new mission to find the truth about secrets from their past, all while facing a new enemy who anticipates their every move. —Blazer346', 'Action,Fantasy', 0, '[\'Paul Rudd\', \'Evangeline Lilly\']', 'https://tse4.mm.bing.net/th?id=OIP.9ayeAytL3S-Nd-KJ_NWvVAHaK-&pid=Api&P=0&w=134&h=199'),
('mn021', 'Captain Marvel', '16', 2019, NULL, 'Movie,Action', 'United States', 'Captain Marvel is an alien Kree warrior who finds herself caught in the middle of a battle between her people and the Skrulls. With help from Nick Fury, she soon tries to uncover the secrets of her past while harnessing her powers t', 'After crashing an experimental aircraft, Air Force pilot Carol Danvers is discovered by the Kree and trained as a member of the elite Starforce Military under the command of her mentor Yon-Rogg. Six years later, after escaping to Earth while under attack by the Skrulls, Danvers begins to discover there\'s more to her past. With help from S.H.I.E.L.D. agent Nick Fury, they set out to unravel the truth. —Blazer346', 'Action,Fantasy', 0, '[\'Brie Larson\', \'Samuel L Jackson\']', 'https://tse2.mm.bing.net/th?id=OIP.GCrmd6ZqyINYUmC1OBqESAHaK-&pid=Api&P=0&w=131&h=194'),
('mn022', 'Avenger: Endgame', '15', 2019, NULL, 'Movie,Action', 'United States', 'The remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the unive', 'Catastrophe. Confusion. Loss. The overwhelming devastation caused by the mad Titan Thanos has left what remains of the Avengers reeling. For a while, all hope seems lost...until an opportunity to reverse the damage is presented. Now, the team must assemble once more and do whatever it takes to restore the universe and bring those they lost. —niteshcongreja', 'Action,Fantasy', 0, '[\'Robert Downey Jr\', \'Chris Evans\', \'Chris Hemsworth\', \'Josh Brolin\']', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_FMjpg_UX1000_.jpg'),
('mn023', 'Spider-Man: Far From Home', '15', 2019, NULL, 'Movie,Action', 'United States', 'Spider-Man teams up with Nick Fury and fellow superhero Mysterio to stop four massive elemental creatures -- each representing Earth, air, water and fire -- from wreaking havoc across Europe.', 'Some time after Thanos was defeated and Tony Stark\'s sacrifice, Peter Parker returns to high school. Now, Peter is out to see the world with his classmates and is wanting to take a break from being Spider-Man. But his fun filled trip is suddenly sabotaged when a string of mysterious attacks by creatures called Elementals start wreaking havoc all over the world. To make matters more difficult, Peter finds himself recruited by Nick Fury and an inter dimensional newcomer named Quentin Beck/Mysterio to help fight them and uncover the truth behind the attacks. —Blazer346', 'Action,Fantasy', 0, '[\'Tom Holland\', \'Zendaya\']', 'https://media.comicbook.com/2019/05/spider-man-far-from-home-poster--1172113.jpeg'),
('mn024', 'Black Widow', '15', 2021, NULL, 'Movie,Action', 'Unites States', 'Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.', 'In Marvel Studios\'s action-packed spy thriller Black Widow, Natasha Romanoff aka Black Widow confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger. —topmeasure', 'Action,Fantasy', 0, '[\'Scarlett Johansen\', \'Florence Pugh\']', 'https://www.themoviedb.org/t/p/original/VVZAjrLperADwEaWR5lD6KeQHu.jpg'),
('mn025', 'Shang-Chi and The Legend of The Ten Rings', '16', 2021, NULL, 'Movie,Action', 'United States', 'Martial-arts master Shang-Chi confronts the past he thought he left behind when he\'s drawn into the web of the mysterious Ten Rings organization.', 'Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.', 'Action,Fantasy', 0, '[\'Simu Liu\', \'Akwafina\']', 'https://tse1.mm.bing.net/th?id=OIP.Xpqx0jbvtMTZFWwNjqvG_AHaKf&pid=Api&P=0&w=109&h=155'),
('mn026', 'Eternals', '16+', 2021, NULL, 'Movie,Action', 'United States', 'The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite to battle the evil Deviants.', 'In 5,000 BC in Babylon, earthlings are attacked by the predator Deviants. The humanoid race of powerful Eternals are awaken in their spaceship by their creator Arishem and unleashed to destroy the Deviants with their abilities. However, they are not authorized to return to their ship and have to stay living on Earth along the centuries. On the present days, in London, the eternal Sersi is walking near the river with her earthling boyfriend Dane Whitman and her friend and also eternal Sprite when they are attacked by a Deviant. Soon the Eternals join themselves to fight the predator race that is more powerful now and they learn dreadful secrets about Arishem and their origins while fighting the predators. —Claudio Carvalho, Rio de Janeiro, Brazil', 'Action,Fantasy', 0, '[\'Angelina Jolie\', \'Gemma Chan\']', 'https://tse3.mm.bing.net/th?id=OIP.30KzOvXfFXqjHkWrEXABhQHaK-&pid=Api&P=0&w=106&h=158'),
('mn027', 'Spider-Man: No Way Home', '12+', 2021, NULL, 'Movie,Action', 'United States', 'When Peter Parker asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'With Spider-Man\'s identity now revealed, our friendly neighborhood web-slinger is unmasked and no longer able to separate his normal life as Peter Parker from the high stakes of being a superhero. When Peter asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man. —krmanirethnam)', 'Action,Fantasy', 0, '[\'Tom Holland\', \'Andrew Garfield\', \'\', \'Tobey Maguire\']', 'https://www.cinemablind.com/wp-content/uploads/2021/11/Spider-Man-No-Way-Home-Poster-543x805.jpg'),
('mn028', 'Doctor Strange in The Multiverse of Madness', '18', 2022, NULL, 'Movie,Action', 'United States', 'With help from old and new allies, Dr. Stephen Strange travels into the multiverse to face a mysterious adversary.', 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.', 'Action,Fantasy', 0, '[\'Benedict Cumberbatch\', \'Rachel McAdams\']', 'https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_FMjpg_UX1000_.jpg'),
('mn029', 'WandaVision', '16+', 2021, 2021, 'TvSeries,Action', 'United States', 'Living suburban lives, Wanda and Vision begin to suspect that everything is not as it seems.', 'Blends the style of classic sitcoms with the MCU, in which Wanda Maximoff and Vision - two super-powered beings living their ideal suburban lives - begin to suspect that everything is not as it seems.', 'Action,Fantasy,TvSeries', 0, '[\'Elizabeth Olsen\', \'Paul Bettany\']', 'https://m.media-amazon.com/images/M/MV5BZGEwYmMwZmMtMTQ3MS00YWNhLWEwMmQtZTU5YTIwZmJjZGQ0XkEyXkFqcGdeQXVyMTI5MzA5MjA1._V1_FMjpg_UX1000_.jpg'),
('mn030', 'Falcon and The Winter Soldier', '16', 2021, 2021, 'TvSeries,Action,TvSeries', 'United States', 'Following the events of \'Avengers: Endgame,\' Sam Wilson/Falcon and Bucky Barnes/Winter Soldier team up in a global adventure that tests their abilities -- and their patience.', 'Following the events of Avengers: Endgame, Sam Wilson/Falcon and Bucky Barnes/Winter Soldier team up in a global adventure that tests their abilities -- and their patience.', 'Action,Fantasy,TvSeries', 0, '[\'Anthony Mackey\', \'Sebastian Stan\']', 'https://m.media-amazon.com/images/M/MV5BODNiODVmYjItM2MyMC00ZWQyLTgyMGYtNzJjMmVmZTY2OTJjXkEyXkFqcGdeQXVyNzk3NDUzNTc@._V1_.jpg'),
('mn031', 'Loki', '15', 2021, 2021, 'TvSeries,Action', 'United States', 'The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.', 'Summaries Loki finds out The Variant\'s plan, but he has his own that will forever alter both their destinies. Loki and the Varaint--Sylvie-- are trapped on the doomed moon of Lamentis after Sylvie\'s tempad is damaged after she uses it to escape the TVA.', 'Action,Fantasy,TvSeries', 0, '[\'Tom Hiddelston\', \'Sophia Di Martino\']', 'https://m.media-amazon.com/images/M/MV5BZjdhNWNiODQtOGU2Ni00MzFjLTgzMTgtOWYwZGMyYzUwYTI0XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_.jpg'),
('mn032', 'Hawkeye', '12+', 2021, 2021, 'TvSeries,Action', 'United States', 'Series based on the Marvel Comics superhero Hawkeye, centering on the adventures of Young Avenger, Kate Bishop, who took on the role after the original Avenger, Clint Barton.', 'Series based on the Marvel Comics superhero Hawkeye, centering on the adventures of Young Avenger, Kate Bishop, who took on the role after the original Avenger, Clint Barton.', 'Action,Fantasy,TvSeries', 0, '[\'Jeremy Renner\', \'Hailee Stanfield\']', 'https://terrigen-cdn-dev.marvel.com/content/prod/2x/hawkeye_lob_crd_04.jpg'),
('mn033', 'What If...?', '18+', 2021, 2021, 'TvSeries,Kids,Animated', 'United States', 'Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head, leading the audience into uncharted territory.', 'What If...? is an animated American web television series based on the Marvel Comics series of the same name. It is the sixteenth television series and the first animated series in the Marvel Cinematic Universe. The series is produced by Marvel Studios and was released on Disney+.', 'Animation,Fantasy,TvSeries', 0, '[\'Jeffrey Wright\', \'Terri Douglas\', \'Matthew Wood\']', 'https://media.comicbook.com/2021/07/marvel-what-if-tv-series-poster-official-disney-plus-1274908.jpeg?auto=webp&width=1280&height=1897&crop=1280:1897,smar'),
('mn034', 'Moon Knight', '13', 2022, 2022, 'TvSeries,Action', 'United States', 'Moon Knight is an American television miniseries created by Jeremy Slater for the Disney+ Hotstar streaming service, based on the Marvel Comics character of the same name. This series belongs to the Marvel Cinematic Universe.', 'Steven Grant discovers he\'s been granted the powers of an Egyptian moon god. But he soon finds out that these newfound powers can be both a blessing and a curse to his troubled life.', 'Action,Fantasy,TvSeries', 0, '[\'Oscar Issac\', \'Ethan Hawke\']', 'https://m.media-amazon.com/images/M/MV5BYTc5OWNhYjktMThlOS00ODUxLTgwNDQtZjdjYjkyM2IwZTZlXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_FMjpg_UX1000_.jpg'),
('mn035', 'Ms. Marvel', '18', 2022, 2022, 'TvSeries,Action', 'United States', 'Kamala feels like she doesn\'t fit in at school and even at home, that is until she gets superpowers. ', 'Marvel Studios’ Ms. Marvel is a new, original series that introduces Kamala Khan, a Muslim American teenager growing up in Jersey City. An avid gamer and a voracious fan-fiction scribe, Kamala is a Super Hero megafan with an oversized imagination—particularly when it comes to Captain Marvel.', 'Action,Fantasy,TvSeries', 0, '[\'Iman Vellani\', \'Aramis Knight\']', 'https://m.media-amazon.com/images/M/MV5BZmQ3OTZkNDUtNTU0Mi00ZjE4LTgyNTUtY2E4NWRmNDUxMzkyXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg'),
('mn036', 'Ultimate Avenger: The Movie', '13+', 2006, NULL, 'Movie,Kids,Animated', 'United States', 'Captain America (Justin Gross), the Hulk, Iron Man (Marc Worden) and other superheroes join forces to save mankind from evil.', 'When a nuclear missile was fired at Washington in 1945, Captain America managed to detonate it in the upper atmosphere. But then he fell miles into the icy depths of the North Atlantic, where he remained lost for over sixty years. But now, with the world facing the very same evil, Captain America must rise again as our last hope for survival.', 'Animation,Fantasy', 0, '[\'Fred Tatasciore\', \'Justin Gross\']', 'https://m.media-amazon.com/images/M/MV5BMTYyMjk0NTMwMl5BMl5BanBnXkFtZTgwNzY0NjAwNzE@._V1_.jpg'),
('mn037', 'Ultimate Avenger 2: Rise of the Panther ', '16+', 2006, NULL, 'Movie,Kids,Animated', 'United States', 'When the Chitauri invaders are sighted in the African kingdom of Wakanda, the Avengers covertly enter the advanced nation to investigate.', 'T\'Challa, the Prince of Wakanda, returns from the outside world to learn the kingdom is being attacked by the alien Chitauri. Herr Kleiser, the alien shape-shifter who battled Captain America during World War II, kills T\' Challa\'s father in combat and seeks Wakanda\'s store of vibranium, the metal the Chitauri use to manufacture their ships and weapons. After becoming King and assuming the alias of the Black Panther, T\' Challa seeks the aid of Captain America. General Nick Fury of S.H.I.E.L.D. orders the Avengers to assemble, with the exception of Thor (who foresees a future in which the Avengers die in battle, which father Odin confirms is connected to a giant spacecraft heading for Earth) and the Hulk, whose alter-ego Bruce Banner is interrogated and bullied in a cell.', 'Animation,Fantasy', 0, '[\'Justin Gross\', \'Grey Griffin\']', 'https://m.media-amazon.com/images/M/MV5BZjI3MTI5ZTYtZmNmNy00OGZmLTlhNWMtNjZiYmYzNDhlOGRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg'),
('mn038', 'The Invincible Iron Man', '13', 2007, NULL, 'Movie,Kids,Animated', 'United States', 'A wealthy inventor (Marc Worden) creates a suit made of impenetrable armor after he unwittingly unleashes an evil force.', 'When a cocky industrialist\'s efforts to raise an ancient Chinese temple leads him to be seriously wounded and captured by enemy forces, he must use his ideas for a revolutionary power armor in order to fight back as a superhero.', 'Animation,Fantasy', 0, '[\'Marc Worden\', \'Gwendoline Yeo\']', 'https://m.media-amazon.com/images/M/MV5BOGRmZDg1YjMtMDA5YS00OTFjLTgyMjQtNDgzNTIyNzAwZDg0L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg'),
('mn039', 'Doctor Strange: The Sorcerer Supreme', '13', 2007, NULL, 'Movie,Kids,Animated', 'United States', 'Doctor Stephen Strange, or simply Doctor Strange, is a master of the mystic arts and deals with many mystic threats.', 'Dr. Stephen Strange is one of the most gifted surgeons in the world, however, he is also highly arrogant and dismissive of his colleagues. While driving home from the hospital one night, he notices Baron Mordo and his allies slaying a monster – notable because they are hidden from view by one of Wong\'s spells.', 'Animation,Fantasy', 0, '[\'Bryce Johnson\', \'Kevin Michael Richardson\']', 'https://m.media-amazon.com/images/M/MV5BZDAxNGFhMDgtZjIwOC00MDhjLTk1MzQtZmRlMWZmNWEzZGU2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg'),
('mn040', 'Next Avengers: Heroes of Tomorrow', '18', 2008, NULL, 'Movie,Kids,Animated', 'United States', 'The teenage offspring (Noah Crawford, Aidan Drummond, Brenna O\'Brien) of famous superheroes battle the powerful villain Ultron.', 'The children of the Avengers hone their powers and go head to head with the very enemy responsible for their parents\' demise.', 'Animation,Fantasy,TvSeries', 0, '[\'Noah Crawford\', \'Brenna O\'Brien\']', 'https://m.media-amazon.com/images/M/MV5BMTQ3NjExNjY4N15BMl5BanBnXkFtZTcwNTczODkwNQ@@._V1_FMjpg_UX1000_.jpg'),
('mn041', 'X-Men: The Animated Series', '16+', 1992, 1997, 'TvSeries,Kids,Animated', 'United States', 'A team of mutant superheroes fight for justice and human acceptance in the Marvel Comics universe.', 'X-Men (also known as X-Men: The Animated Series) is an animated superhero television series which debuted on October 31, 1992, in the United States on the Fox Kids Network. X-Men was Marvel Comics\' second attempt at an animated X-Men TV series after the pilot, X-Men: Pryde of the X-Men, was not picked up.', 'Animation,Fantasy,TvSeries', 0, '[\'Cedric Smith\', \'Cal Dodd\']', 'https://m.media-amazon.com/images/M/MV5BNTVjNmEwNTMtNmQ2ZC00MGJkLWI3MDgtNzMyNTc4YjVkNTQ1L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg'),
('mn042', 'Iron Man', '13', 1994, 1996, 'TvSeries,Kids,Animated', 'United States', 'Industrialist Tony Stark leads his private team of superheros as Iron Man against the forces of evil.', 'When billionaire industrialist, Tony Stark, dons his solar-charged, steel-mesh armour, he becomes the invincible Iron Man, ready to do battle with the villainous Mandarin and the power of his ten deadly rings. To protect his company, Stark Enterprises, from the threat posed by the team of Mandarin, Stark\'s rival Justin Hammer, and their team of super-powered followers, Iron Man is joined by Force Works, his own team of allies and friends, who time and again claim victory over their foes. When Tony fakes his own death, enabling a pivotal battle to be won and for the Mandarin to apparently be destroyed, he inadvertantly alienates his team-mates, causing Force Works to disband. Now, with a new, more powerful armour that adapts to different environments, Iron Man must face a multitude of new foes - and his own personal demons, as well. —Chris McFeely', 'Animation,Fantasy,TvSeries', 0, '[\'Ryan Eggold\', \'Janet Montgomery\', \'Freema Agyeman\']', 'https://m.media-amazon.com/images/M/MV5BNDJjMDI0YzQtOWM2OC00NmJhLTk3YWMtYmY5NDBkZmVlM2NjXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_FMjpg_UX1000_.jpg'),
('mn043', 'Fantastic Four: The Animated Series', '16+', 1994, 1996, 'TvSeries,Kids,Animated', 'United States', 'The adventures of Marvel Comic\'s greatest superhero team.', 'A rocket carrying four young people--scientific genius Reed Richards, his World War II buddy Ben Grimm, his wife Sue Richards and Sue\'s hot-headed brother Johnny Storm--is bombarded by cosmic rays while orbiting the Earth. The radiation gives them special powers: Richards can now stretch his limbs, Johnny can burst into flame, Sue can render herself invisible, while Ben has been physically transformed into a big orange rock and given super-strength. They decide to name themselves The Fantastic Four, and use their powers to battle world-dominating villains such as Doctor Doom and The Mole Man. —Marty McKee ', 'Animated,Fantasy,TvSeries', 0, '[\'Claire Foy\', \'Olivia Colman\', \'Imelda Staunton\']', 'https://m.media-amazon.com/images/M/MV5BYWNlMzlmZTctMDlhNi00MWYzLThkZGMtNGI3YWViMTIxNjRkXkEyXkFqcGdeQXVyOTkwMTc4ODQ@._V1_FMjpg_UX1000_.jpg'),
('mn044', 'Spider-Man: The Animated Series', '18', 1994, 1998, 'TvSeries,Kids,Animated', 'United States', 'A young man with spider-like abilities fights crime as a superhero in New York City while trying to have a normal personal life.', 'The Friendly Neighbourhood Spider-Man comes to life in this cult-classic from the 1990s; bringing iconic stories to life ranging from The Symbiote Saga to Secret Wars. One of Marvel Animation\'s crowning achievements: Spider-Man: The Animated Series. —Johnny-the-Film-Sentinel-2187', 'Animation,Fantasy,TvSeries', 0, '[\'Richard Armitage\', \'James Callis\', \'Alejandra Reynoso\']', 'https://m.media-amazon.com/images/M/MV5BMmQ1NzBlYmItNmZkZi00OTZkLTg5YTEtNTI5YjczZjk3Yjc1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg'),
('mn045', 'The Incredible Hulk', '13', 1996, 1998, 'TvSeries,Kids,Animated', 'United States', 'A nuclear scientist is afflicted with the tendency to change into a powerful green monster under stress.', 'Based on Marvel\'s famous comic hero, this animated series presents the adventures of Dr. Robert Bruce Banner. An accident during the test of the Gamma Bomb (Banner\'s creation) transformed him into a powerful hulking being; since then he is on the run because the Army believes him to be a threat which must be destroyed. —Chris Makrozahopoulos ', 'Animation,Fantasy,TvSeries', 0, '[\'Daniel Lapaine\', \'Hannah John-Kamen\', \'Michaela Coel\']', 'https://m.media-amazon.com/images/M/MV5BYmVjYzA3MmYtZjBhOS00OGI5LWIzZTEtOTRkZGY2ZWQ5NjkzXkEyXkFqcGdeQXVyNzMzMjU5NDY@._V1_.jpg'),
('mn046', 'Silver Surfer', '13', 1998, 1998, 'TvSeries,Kids,Animated', 'United States', 'The adventures of the cosmic wanderer as he seeks his lost home after rebelling from his master.', 'When the planet Zenn-La is threatened by the cosmic giant Galactus, a being that must drain whole planets of their lifeforce for sustenance, Norrin Radd must act. He makes a bargain to be the scout for the being, to search for uninhabited planets, in return for for Zenn-La\'s survival. Galactus agrees to this and changes the man into the powerful Silver Surfer, but he also submerges his humanity to remove his qualms about selecting populated planets for consumption. That suppression is only broken by an attack by the insane space villain, Thanos. With the knowledge of Galactus\' treachery, he moves to stop the being just as he was going to consume Earth. With difficulty, the Surfer manages to stop him and breaks all ties to Galactus. In retaliation, Galactus whisks Zenn-La to an unknown location and now the former Herald must search for his lost home. However, there are few clues and while he still has all his might of the Power Cosmic, there are many races who want their revenge for the destruction he brought to their homes as the servant of Galactus. —Kenneth Chisholm', 'Action,Fantasy,TvSeries', 0, '[\'Lady Gaga\', \'Kathy Bates\', \'Angela Bassett\']', 'https://m.media-amazon.com/images/M/MV5BZjJlZmY5MDctMjZhMC00YzgwLTk0MTItZTM5OGFlMDU4MjA4XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg'),
('mn047', 'Spider-Man Unlimited', '13', 1995, 2005, 'TvSeries,Kids,Animated', 'United States', 'Spider-Man travels to Counter-Earth to rescue a Terran shuttle crew trapped there and discovers a tyrannical and warped version of his world.', 'Covering a shuttle launch to the planet known as Counter-Earth, Peter Parker discovers the symbiote villians, Venom and Carnage, boarding the craft as it launches. When he is unable to stop them as Spider-Man and contact is lost with the shuttle, he is blamed for the disaster and hunted until he is believed to have been killed in a fire. Peter does survive and is content to lie low until he learns that the crew is alive, but trapped on Counter-Earth. Gaining a new costume and weapons from Reed Richards of the Fantastic Four, he boards a second shuttle to rescue the crew and travels to the planet. Shot down, he finds must get involved in a fight against the tyranny of the planet\'s ruler, The High Evolutionary and distorted copies of his old enemies on this new world. —Kenneth Chisholm', 'Animation,Fantasy,TvSeries', 0, '[\'Eliza Taylor\', \'Bob Morley\', \'Marie Avgeropoulos\']', 'https://m.media-amazon.com/images/M/MV5BZTYwMmE5M2EtYWNhOS00MGZhLWFiYmEtMjVhYTYxODA1NTZhXkEyXkFqcGdeQXVyMTI1MzYzODMy._V1_.jpg'),
('mn048', 'Avengers: United They Stand', '18', 1999, 2000, 'TvSeries,Kids,Animated', 'United States', 'The adventures of the Marvel Comics Universe\'s greatest general membership superhero team.', 'The Avengers: United They Stand is an animated series featuring the Avengers in their adventures fighting crime and villainy.', 'Animation,Fantasy,TvSeries', 0, '[\'Alice Braga\', \'Hemky Madera\', \'Peter Gadiot\']', 'https://m.media-amazon.com/images/M/MV5BNDg0MzM1MWQtMDI3ZC00NDY4LTk4MjYtMjdjNDZlNzk3MTY5XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_FMjpg_UX1000_.jpg'),
('mn049', 'X-Men: Evolution', '15+', 2000, 2003, 'TvSeries,Kids,Animated', 'United States', 'This rendition of X-Men features Cyclops, Jean Grey, Rogue, Nightcrawler, Shadowcat and Spike as teenagers as they fight for a world that fears and hates them.', 'Professor Charles Francis Xavier, who has the mutant ability to read minds, searches for new mutants to train them how to use their powers for good and to prevent the mutants from harming themselves and others at his School for Gifted Youngsters. His opposition, Magneto \"Master of Magnetism\", is doing the same thing, but for evil purposes. He has made Mystique who is a shape-shifter, a principle of his high school to gather evil mutants to prepare them for war against non-mutants. The most interesting plot of the story is that all the heroes and villains attend the same high school. The classic battle of good vs. evil has begun again. —Emmett Dweh', 'Animation,Fantasy,TvSeries', 0, '[\'Josh Radnor\', \'Jason Segel\', \'Cobie Smulders\']', 'https://m.media-amazon.com/images/M/MV5BOWMyMThhN2UtMGMzYi00ODVmLWFlODItYmZlMzMxYzE3MmZkXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_.jpg'),
('mn050', 'Iron Man: Armored Adventures', '16+', 2008, 2012, 'TvSeries,Kids,Animated', 'United States', 'A teenage Tony Stark battles evil with his revolutionary power armor technology.', 'A young man tries to balance the pressure of teenage life with the duties of being a superhero.', 'Animation,Fantasy,TvSeries', 0, '[\'Jason Bateman\', \'Laura Linney\', \'Sofia Hublitz\']', 'https://m.media-amazon.com/images/M/MV5BZWNjZTJjZmYtYjhjZS00ZjgwLWFjY2UtMzBlMDkzZmM3M2FiXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`imdb_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
